# ============================================================================
# RecurrentStates: a renewal over states (semi-Markov), the default cyclic mode
# ============================================================================
#
# The acyclic composer tree runs each event once and accumulates times forward,
# so it cannot represent a cycle (relapse, reinfection, admit/discharge
# cycling): a path that returns to a state and takes an unbounded, random number
# of steps. `RecurrentStates` lifts that limit as a RENEWAL OVER STATES.
#
# Each non-absorbing state owns a TRANSITION node over its outgoing edges -- a
# racing-hazard `Compete` (which-and-when coupled), a fixed-probability
# `Resolve` (split independent of timing), or a lone bare edge. A path starts
# in `start`, draws the winning next-state and its sojourn from the current
# state's node, RESETS the clock on entry (the semi-Markov holding time), and
# repeats until an absorbing state (no outgoing edges) or a horizon. A back edge
# is just an edge whose destination is an already-visited state, so cycles fall
# out with no new machinery: the only addition over the acyclic grammar is the
# loop that unfolds the steps.
#
# Every per-step quantity reuses the existing verbs. The sojourn on an edge is
# ANY `UnivariateDistribution` (a plain, censored, modified or composed delay),
# the cause-resolved per-edge log sub-density is the `Compete` term the package
# already computes, the winning draw is `rand_outcome`, and the per-edge prior
# inventory is the standard `params`/`params_table` machinery. The memoryless
# special case (exponential edges, panel-observed data) has a CTMC fast path in
# `CTMCStates.jl`.

@doc raw"""

A renewal over states: a semi-Markov multi-state model that admits cycles.

`RecurrentStates` maps each non-absorbing state to a transition node over its
outgoing edges and a `start` state. A realisation is a PATH: a sequence of
``(\text{from}, \text{to}, \text{dwell})`` jumps generated by repeatedly drawing
the winning next-state and its sojourn from the current state's node and
resetting the clock on entry, until an absorbing state or a horizon. Because an
edge's destination may be an already-visited state, paths may cycle (relapse,
reinfection, hospital admit/discharge cycling), which the acyclic composer tree
cannot represent.

Build it with the [`recur`](@ref) verb. Each state's node is a
[`Compete`](@ref) (racing hazards), a [`Resolve`](@ref) (fixed split), or a lone
bare edge; the sojourn on any edge is any `UnivariateDistribution`, including a
censored or composed delay.

The path log-density is the sum of the per-sojourn transition log sub-densities
(the `Compete`/`Resolve` cause-resolved term), so it factorises over steps and
is AD-safe; [`logpdf`](@ref) scores a path and [`rand`](@ref) simulates one. The
memoryless special case (exponential edges, panel data) has a CTMC fast path,
[`ctmc`](@ref).

# Fields
- `nodes`: a `Dict` mapping each non-absorbing state (a `Symbol`) to its
  transition node (a [`Compete`](@ref), [`Resolve`](@ref), or a lone
  `dest => dist` `Pair`).
- `start`: the state a path begins in (a `Symbol`).

# See also
- [`recur`](@ref): the constructor verb.
- [`ctmc`](@ref): the memoryless CTMC fast path.
- [`Compete`](@ref), [`Resolve`](@ref): the per-state transition nodes.
"""
struct RecurrentStates{N, S}
    "State -> transition node (`Compete` / `Resolve` / lone `dest => dist`)."
    nodes::N
    "The state a path begins in."
    start::S

    function RecurrentStates(nodes::N, start::S) where {N <: AbstractDict, S}
        start isa Symbol ||
            throw(ArgumentError("the start state must be a Symbol"))
        _validate_state_graph(nodes, start)
        return new{N, S}(nodes, start)
    end
end

# The destination states an edge / node points to. A lone edge points to its
# `dest`; a one_of node points to each outcome name (the destination states).
_edge_dests(p::Pair) = (p.first,)
_edge_dests(c::AbstractOneOf) = component_names(c)

# The sojourn distribution(s) of a node, aligned with `_edge_dests`.
_edge_dists(p::Pair) = (p.second,)
_edge_dists(c::AbstractOneOf) = c.delays

# A node must be a one_of node (>= 2 edges) or a lone `dest => dist` edge.
_is_transition_node(::AbstractOneOf) = true
_is_transition_node(p::Pair) = p.first isa Symbol && _is_one_of_branch(p.second)
_is_transition_node(::Any) = false

# Validate the state graph: every node is a transition node, every edge points
# to a known state (an existing key or an absorbing leaf), and the start state
# is itself a node or a lone absorbing state with an inbound edge.
function _validate_state_graph(nodes::AbstractDict, start::Symbol)
    isempty(nodes) &&
        throw(ArgumentError("a RecurrentStates needs at least one state node"))
    all(k -> k isa Symbol, keys(nodes)) ||
        throw(ArgumentError("every state name must be a Symbol"))
    for (state, node) in nodes
        _is_transition_node(node) || throw(ArgumentError(
            "state $(state) must map to a Compete / Resolve node or a lone " *
            "`dest => dist` edge; got $(typeof(node))"))
        for d in _edge_dests(node)
            d isa Symbol || throw(ArgumentError(
                "every edge destination must be a Symbol; state $(state) has " *
                "a non-Symbol destination"))
        end
    end
    # The start state must lead somewhere (be a node) unless it is the lone
    # state of a degenerate one-step graph; an absorbing start is a no-op path.
    haskey(nodes, start) || _any_edge_into(nodes, start) ||
        throw(ArgumentError(
            "the start state $(start) is neither a transition node nor the " *
            "destination of any edge; it cannot begin a path"))
    return nothing
end

# Whether any node has an edge into `state` (so an absorbing start/destination
# is reachable rather than a typo).
function _any_edge_into(nodes::AbstractDict, state::Symbol)
    for node in values(nodes)
        state in _edge_dests(node) && return true
    end
    return false
end

@doc raw"""

Build a [`RecurrentStates`](@ref) renewal-over-states model from
`state => transitions` specifications.

Each argument is `state => transitions`, where `transitions` lists the outgoing
edges of `state`. A state with one outgoing edge takes a single
`next_state => sojourn` pair; a state with several outgoing edges takes a tuple
of them, building a racing-hazard [`Compete`](@ref) node (bare sojourns) or a
fixed-probability [`Resolve`](@ref) node (`(sojourn, prob)` payloads). A state
with no `state =>` entry is absorbing (a path ends there). The first argument's
state is the `start` state unless `start` is given.

The sojourn on any edge is any `UnivariateDistribution`, including a censored or
composed delay. An edge may point back to an already-visited state, so the model
admits cycles.

# Arguments
- `specs`: `state => transitions` pairs. `transitions` is a single
  `next_state => sojourn` pair (a lone edge), or a tuple / NamedTuple of
  `next_state => sojourn` (racing hazards) or `next_state => (sojourn, prob)`
  (a fixed split) edges.

# Keyword Arguments
- `start`: the state a path begins in (default: the first spec's state).

# Examples
```@example
using CensoredDistributions, Distributions

# A waning-immunity reinfection cycle: recovered -> susceptible closes the loop.
model = recur(
    :susceptible => (:infected => Gamma(2.0, 4.0)),
    :infected => (:recovered => Gamma(2.0, 3.0), :dead => Gamma(2.0, 8.0)),
    :recovered => (:susceptible => Gamma(2.0, 30.0)))
rand(model; horizon = 90.0)
```

# See also
- [`RecurrentStates`](@ref): the model type.
- [`ctmc`](@ref): the memoryless CTMC fast path.
- [`compete`](@ref), [`resolve`](@ref): the per-state transition constructors.
"""
function recur(specs::Pair...; start::Union{Symbol, Nothing} = nothing)
    isempty(specs) &&
        throw(ArgumentError("recur needs at least one state spec"))
    nodes = Dict{Symbol, Any}()
    for (state, transitions) in specs
        state isa Symbol ||
            throw(ArgumentError("each state name must be a Symbol; got $state"))
        haskey(nodes, state) &&
            throw(ArgumentError("state $(state) is specified more than once"))
        nodes[state] = _build_transition_node(transitions)
    end
    s = start === nothing ? first(specs).first : start
    return RecurrentStates(nodes, s)
end

# Build a state's transition node from its outgoing-edge spec. A lone
# `dest => dist` pair stays a bare edge; a tuple / NamedTuple of edges lowers to
# `compete` (bare delays) or `resolve` (`(delay, prob)` payloads) by reusing the
# existing one_of constructor dispatch.
_build_transition_node(p::Pair) = _validated_edge(p)
function _build_transition_node(edges::Tuple)
    length(edges) == 1 && return _validated_edge(only(edges))
    payloads = map(e -> e.second, edges)
    # A `(delay, prob)` payload anywhere selects the fixed-probability split;
    # all-bare delays race. This mirrors the `resolve` / `compete` split so a
    # state's node is built by the same rules as a standalone one_of node.
    return any(_is_prob_payload, payloads) ? resolve(edges...) :
           compete(edges...)
end
function _build_transition_node(edges::NamedTuple)
    return _build_transition_node(_nt_pairs(edges))
end
function _build_transition_node(x)
    throw(ArgumentError(
        "a state's transitions must be a single `dest => sojourn` edge or a " *
        "tuple / NamedTuple of edges; got $(typeof(x))"))
end

# A lone edge must be `dest::Symbol => sojourn`.
function _validated_edge(p::Pair)
    p.first isa Symbol || throw(ArgumentError(
        "an edge destination must be a Symbol; got $(typeof(p.first))"))
    _is_one_of_branch(p.second) || throw(ArgumentError(
        "an edge sojourn must be a UnivariateDistribution or composer " *
        "subtree; got $(typeof(p.second))"))
    return p
end

# --- accessors --------------------------------------------------------------

@doc """

The states of a [`RecurrentStates`](@ref) model that have outgoing edges
(the non-absorbing states), as a sorted vector.

# Arguments
- `m`: the [`RecurrentStates`](@ref) model to read.

# Examples
```@example
using CensoredDistributions, Distributions

m = recur(:well => (:ill => Gamma(2.0, 5.0)),
    :ill => (:dead => Gamma(2.0, 3.0),))
CensoredDistributions.transient_states(m)
```

See also: [`absorbing_states`](@ref)
"""
transient_states(m::RecurrentStates) = sort!(collect(keys(m.nodes)))

@doc """

The absorbing states of a [`RecurrentStates`](@ref) model (edge destinations
with no outgoing edges of their own), as a sorted vector. A path ends on
reaching one.

# Arguments
- `m`: the [`RecurrentStates`](@ref) model to read.

# Examples
```@example
using CensoredDistributions, Distributions

m = recur(:well => (:ill => Gamma(2.0, 5.0)),
    :ill => (:dead => Gamma(2.0, 3.0),))
CensoredDistributions.absorbing_states(m)
```

See also: [`transient_states`](@ref)
"""
function absorbing_states(m::RecurrentStates)
    dests = Set{Symbol}()
    for node in values(m.nodes)
        for d in _edge_dests(node)
            haskey(m.nodes, d) || push!(dests, d)
        end
    end
    return sort!(collect(dests))
end

@doc """

Whether `state` is absorbing in a [`RecurrentStates`](@ref) model: it has no
outgoing edges, so a path that reaches it ends.

# Arguments
- `m`: the [`RecurrentStates`](@ref) model.
- `state`: the state to test.

# Examples
```@example
using CensoredDistributions, Distributions

m = recur(:well => (:ill => Gamma(2.0, 5.0)),
    :ill => (:dead => Gamma(2.0, 3.0),))
CensoredDistributions.is_absorbing(m, :dead)
```

See also: [`absorbing_states`](@ref), [`transient_states`](@ref)
"""
is_absorbing(m::RecurrentStates, state::Symbol) = !haskey(m.nodes, state)

function Base.show(io::IO, m::RecurrentStates)
    print(io, "RecurrentStates(", length(m.nodes), " states, start=",
        m.start, ")")
    return nothing
end

function Base.show(io::IO, ::MIME"text/plain", m::RecurrentStates)
    println(io, "RecurrentStates renewal-over-states model")
    println(io, "  start: ", m.start)
    for state in transient_states(m)
        node = m.nodes[state]
        dests = join(string.(_edge_dests(node)), ", ")
        println(io, "  ", state, " -> {", dests, "}")
    end
    abss = absorbing_states(m)
    isempty(abss) || print(io, "  absorbing: ", join(string.(abss), ", "))
    return nothing
end
