name = "primarycensored"
uuid = "b2eeebe4-5992-4301-9193-7ebc9f62c855"
authors = ["Samuel Abbott", "Damon Bayer", "Michael DeWitt", "Joseph Lemaitre"]
version = "0.1.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = ">= 0.9.0"
julia = ">= 1.9"
