name = "CensoredDistributions"
uuid = "b2eeebe4-5992-4301-9193-7ebc9f62c855"
license = "MIT"
authors = ["Sam Abbott", "Damon Bayer", "Sam Brand", "Michael DeWitt", "Joseph Lemaitre"]
version = "0.2.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.25"
DocStringExtensions = "0.9"
HypergeometricFunctions = "0.3"
Integrals = "4"
LogExpFunctions = "0.3"
Optimization = "4"
OptimizationOptimJL = "0.4.3"
Random = "1"
SpecialFunctions = "2"
Statistics = "1"
julia = "1.10, 1.11, 1.12"
