name = "CensoredDistributions"
uuid = "b2eeebe4-5992-4301-9193-7ebc9f62c855"
authors = ["Samuel Abbott", "Damon Bayer", "Michael DeWitt", "Joseph Lemaitre"]
version = "0.1.0-DEV"
license = "MIT"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Distributions = ">= 0.25"
DocStringExtensions = ">= 0.9.0"
Integrals = ">= 4.5"
LogExpFunctions = ">= 0.3"
Random = ">= 1.10"
SpecialFunctions = ">= 2.0"
julia = ">= 1.10"
