name = "CensoredDistributions"
uuid = "b2eeebe4-5992-4301-9193-7ebc9f62c855"
license = "MIT"
authors = ["Samuel Abbott", "Damon Bayer", "Michael DeWitt", "Joseph Lemaitre"]
version = "0.1.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"

[extensions]
OptimizationExt = ["Optimization"]

[compat]
Bijectors = ">= 0.15"
Distributions = ">= 0.25"
DocStringExtensions = ">= 0.9.0"
Integrals = ">= 4.5"
LogExpFunctions = ">= 0.3"
Optimization = ">= 3.28"
OptimizationOptimJL = ">= 0.3"
Random = ">= 1.10"
SpecialFunctions = ">= 2.0"
Statistics = ">= 1.10"
julia = ">= 1.10"
