name = "primarycensored"
uuid = "b2eeebe4-5992-4301-9193-7ebc9f62c855"
authors = ["Samuel Abbott <azw1@cdc.gov>", "Samuel Brand <usi1@cdc.gov>"]
version = "0.1.0-DEV"

[deps]

[compat]
julia = ">= 1.9"
