"""
Post-process PlutoStaticHTML output to convert HTML code blocks to markdown fences
and wrap HTML content in @raw html blocks for proper VitePress rendering.

This handles two scenarios:
1. Original PlutoStaticHTML output (HTML code blocks in @raw html wrapper)
2. Already-processed content (markdown fences + unwrapped HTML)
"""
function postprocess_pluto_markdown(content::AbstractString)
    # Remove PlutoStaticHTML markers and state block
    content = replace(content, r"<!-- PlutoStaticHTML\.Begin -->\s*" => "")
    content = replace(content, r"<!-- PlutoStaticHTML\.End -->\s*" => "")
    content = replace(content,
        r"<!--\s*# This information is used for caching\..*?\[PlutoStaticHTML\.State\].*?-->\s*"s => "")

    # Remove the outer ```@raw html wrapper if present
    content = replace(content, r"^```@raw html\n"m => "")
    content = replace(content, r"\n```\s*$"m => "")

    # Remove the PlutoStaticHTML style block
    content = replace(content,
        r"<style>\s*#documenter-page.*?</style>\s*"s => "")

    # Clean up empty markdown divs
    content = replace(content, r"<div class=\"markdown\"></div>\s*"s => "")

    # Convert any remaining HTML code blocks to markdown fences
    content = replace(content,
        r"<pre class=['\"]language-julia['\"]><code class=['\"]language-julia['\"]>(.*?)</code></pre>"s => s"```julia\n\1\n```")

    # Convert HTML output blocks to VitePress details
    content = replace(content,
        r"<pre class=\"code-output documenter-example-output\"[^>]*>(.*?)</pre>"s => s"::: details Output\n```\n\1\n```\n:::")

    # Now wrap HTML sections in @raw html blocks
    # Split content by markdown elements (code fences, details blocks)
    # and wrap HTML-containing sections

    lines = split(content, '\n')
    result = IOBuffer()
    html_buffer = IOBuffer()
    in_code_block = false
    in_details = false

    for line in lines
        # Track code blocks
        if startswith(line, "```julia") || startswith(line, "```@")
            in_code_block = true
        elseif startswith(line, "```") && in_code_block
            in_code_block = false
        end

        # Track details blocks
        if startswith(line, "::: details")
            in_details = true
        elseif line == ":::" && in_details
            in_details = false
        end

        # Check if this line contains HTML (outside code/details blocks)
        has_html = !in_code_block && !in_details && occursin(r"<[a-zA-Z/]", line)

        if has_html
            # Add to HTML buffer
            println(html_buffer, line)
        else
            # Flush HTML buffer if not empty
            html_content = String(take!(html_buffer))
            if !isempty(strip(html_content))
                println(result, "```@raw html")
                print(result, html_content)
                println(result, "```")
                println(result)
            end
            # Write non-HTML line
            println(result, line)
        end
    end

    # Flush any remaining HTML buffer
    html_content = String(take!(html_buffer))
    if !isempty(strip(html_content))
        println(result, "```@raw html")
        print(result, html_content)
        println(result, "```")
    end

    processed = String(take!(result))

    # Clean up empty raw blocks
    processed = replace(processed, r"```@raw html\n\s*```"s => "")

    # Clean up excessive newlines
    processed = replace(processed, r"\n{4,}" => "\n\n\n")

    return processed
end

"""Run all Pluto notebooks (".jl" files) in `tutorials_dir` and write outputs to HTML files."""
function build(target_subdir; _module = CensoredDistributions)
    target_dir = joinpath(pkgdir(_module), "docs", "src", target_subdir)

    @info "Building notebooks in $target_subdir"
    # Evaluate notebooks in the same process to avoid having to recompile from scratch each time.
    # This is similar to how DocumenterVitepress and Franklin evaluate code.
    # Note that things like method overrides and other global changes may leak between notebooks!
    use_distributed = false
    output_format = documenter_output
    bopts = BuildOptions(target_dir; use_distributed, output_format)
    build_notebooks(bopts)

    # Post-process generated markdown files for VitePress compatibility
    # Only process files that were generated by PlutoStaticHTML (contain the marker)
    @info "Post-processing markdown for VitePress compatibility"
    for file in readdir(target_dir)
        if endswith(file, ".md")
            filepath = joinpath(target_dir, file)
            content = read(filepath, String)
            # Only process Pluto-generated files (contain PlutoStaticHTML marker)
            if occursin("PlutoStaticHTML.Begin", content)
                processed = postprocess_pluto_markdown(content)
                write(filepath, processed)
                @info "  Processed: $file"
            else
                @info "  Skipped (not Pluto-generated): $file"
            end
        end
    end

    return nothing
end

"Return Markdown file links which can be passed to DocumenterVitepress.jl."
function markdown_files(notebook_titles, target_subdir)
    md_files = map(notebook_titles) do title
        file = lowercase(replace(title, " " => '_'))
        return joinpath(target_subdir, "$file.md")
    end
    return md_files
end
