"""
Header content for the release notes page.
This will be combined with NEWS.md during documentation build.
"""

const RELEASE_NOTES_HEADER = """
```@meta
EditURL = "https://github.com/EpiAware/CensoredDistributions.jl/blob/main/NEWS.md"
```

# Release notes

CensoredDistributions.jl follows a hybrid changelog approach:
- **GitHub Releases**: All releases (automatically generated by TagBot)
- **NEWS.md**: Major releases requiring detailed context

See [GitHub Releases](https://github.com/EpiAware/CensoredDistributions.jl/releases) for minor/patch release information.

"""
