name: AD Enzyme reverse

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enzyme-reverse:
    uses: ./.github/workflows/ad-backend.yaml
    with:
      name: Enzyme reverse
      tag: enzyme_reverse
