name: AD Mooncake forward

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mooncake-forward:
    uses: ./.github/workflows/ad-backend.yaml
    with:
      name: Mooncake forward
      tag: mooncake_forward
