name: AD ReverseDiff

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reversediff:
    uses: ./.github/workflows/ad-backend.yaml
    with:
      name: ReverseDiff (tape)
      tag: reversediff
