name: Auto Version Increment

on:
  push:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version changed
        id: version-check
        run: |
          # Get the version from current commit
          CURRENT_VERSION=$(grep '^version = ' Project.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $CURRENT_VERSION"

          # Get the version from previous commit
          git show HEAD~1:Project.toml > Project.toml.prev
          PREV_VERSION=$(grep '^version = ' Project.toml.prev | sed 's/version = "\(.*\)"/\1/')
          echo "Previous version: $PREV_VERSION"

          # Check if version changed
          if [ "$CURRENT_VERSION" = "$PREV_VERSION" ]; then
            echo "Version unchanged, need to increment"
            echo "needs_increment=true" >> $GITHUB_OUTPUT
          else
            echo "Version already changed, no action needed"
            echo "needs_increment=false" >> $GITHUB_OUTPUT
          fi

      - name: Increment version automatically
        if: steps.version-check.outputs.needs_increment == 'true'
        uses: ./.github/actions/increment-version
        with:
          increment-type: patch
          pr-title-prefix: "chore: auto-increment version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
