name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@9692b37b9127099d9c1a51db5034a084edaeb56e
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
