name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@de0f8f56ec29481854592c5e80602eee381febfe
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
