name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@c758269c3e60b7148e9f15d7f0d493aaa4fb8ffc
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
