name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  doc-preview-cleanup:
    uses: EpiAware/.github/.github/workflows/docs-preview-cleanup.yml@de0f8f56ec29481854592c5e80602eee381febfe
    secrets: inherit  # pragma: allowlist secret
