name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    uses: EpiAware/.github/.github/workflows/format-check.yml@de0f8f56ec29481854592c5e80602eee381febfe
    secrets: inherit  # pragma: allowlist secret
