name: Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: EpiAware/.github/.github/workflows/tests.yml@9692b37b9127099d9c1a51db5034a084edaeb56e
    secrets: inherit  # pragma: allowlist secret

  downgrade-compat:
    uses: EpiAware/.github/.github/workflows/downgrade.yml@9692b37b9127099d9c1a51db5034a084edaeb56e
    secrets: inherit  # pragma: allowlist secret
