name: Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: true
      matrix:
        julia-version: ['1', 'lts', 'pre']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - julia-version: 'pre'
            experimental: true
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          test_args: ${{ (matrix.julia-version != '1' || matrix.os == 'windows-latest') && 'skip_quality' || '' }}
